session_name: sandbox-blog
windows:
  - window_name: vim
    focus: true
    window_index: 1
    layout: main-horizontal
    panes:
      - shell_command:
        - vim
        focus: true
      - shell_command:
        - firefox blog/html/index.html &
        - workon py-3.5.2
        - clear
        - pwd

