session_name: sandbox-blog
windows:
  - window_name: vim
    focus: true
    window_index: 1
    layout: main-vertical
    panes:
      - shell_command:
        - vim
        focus: true
      - shell_command:
        - workon py-2.7.12
        - pwd
      - shell_command:
        - firefox blog/html/index.html &

